name: Manual Build
on:
  puspush: :
    branches: ["main", "aaa"]
  workflow_dispatch:



jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy build to target
        run: echo "asas"
